/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) centroidal_mpc_hpipm_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {300, 1, 1};

/* centroidal_mpc_hpipm_dyn_disc_phi_fun:(i0[12],i1[12],i2[300])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26;
  a00=arg[2]? arg[2][0] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][12] : 0;
  a03=arg[0]? arg[0][1] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][24] : 0;
  a04=arg[0]? arg[0][2] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][36] : 0;
  a05=arg[0]? arg[0][3] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][48] : 0;
  a06=arg[0]? arg[0][4] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][60] : 0;
  a07=arg[0]? arg[0][5] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][72] : 0;
  a08=arg[0]? arg[0][6] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][84] : 0;
  a09=arg[0]? arg[0][7] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][96] : 0;
  a10=arg[0]? arg[0][8] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][108] : 0;
  a11=arg[0]? arg[0][9] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][120] : 0;
  a12=arg[0]? arg[0][10] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][132] : 0;
  a13=arg[0]? arg[0][11] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][144] : 0;
  a14=arg[1]? arg[1][0] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][156] : 0;
  a16=arg[1]? arg[1][1] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][168] : 0;
  a17=arg[1]? arg[1][2] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][180] : 0;
  a18=arg[1]? arg[1][3] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][192] : 0;
  a19=arg[1]? arg[1][4] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][204] : 0;
  a20=arg[1]? arg[1][5] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][216] : 0;
  a21=arg[1]? arg[1][6] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][228] : 0;
  a22=arg[1]? arg[1][7] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][240] : 0;
  a23=arg[1]? arg[1][8] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][252] : 0;
  a24=arg[1]? arg[1][9] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][264] : 0;
  a25=arg[1]? arg[1][10] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][276] : 0;
  a26=arg[1]? arg[1][11] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][288] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[2]? arg[2][1] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][13] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][25] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][37] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][49] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][61] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][73] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][85] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][97] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][109] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][121] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][133] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][145] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][157] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][169] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][181] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][193] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][205] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][217] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][229] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][241] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][253] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][265] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][277] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][289] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[2]? arg[2][2] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][14] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][26] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][38] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][50] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][62] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][74] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][86] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][98] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][110] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][122] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][134] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][146] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][158] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][170] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][182] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][194] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][206] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][218] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][230] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][242] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][254] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][266] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][278] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][290] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[2]? arg[2][3] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][15] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][27] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][39] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][51] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][63] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][75] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][87] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][99] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][111] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][123] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][135] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][147] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][159] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][171] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][183] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][195] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][207] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][219] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][231] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][243] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][255] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][267] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][279] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][291] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[2]? arg[2][4] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][16] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][28] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][40] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][52] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][64] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][76] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][88] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][100] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][112] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][124] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][136] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][148] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][160] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][172] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][184] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][196] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][208] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][220] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][232] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][244] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][256] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][268] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][280] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][292] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[2]? arg[2][5] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][17] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][29] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][41] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][53] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][65] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][77] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][89] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][101] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][113] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][125] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][137] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][149] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][161] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][173] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][185] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][197] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][209] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][221] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][233] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][245] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][257] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][269] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][281] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][293] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[2]? arg[2][6] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][18] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][30] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][42] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][54] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][66] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][78] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][90] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][102] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][114] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][126] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][138] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][150] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][162] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][174] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][186] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][198] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][210] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][222] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][234] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][246] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][258] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][270] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][282] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][294] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[2]? arg[2][7] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][19] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][31] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][43] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][55] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][67] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][79] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][91] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][103] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][115] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][127] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][139] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][151] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][163] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][175] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][187] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][199] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][211] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][223] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][235] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][247] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][259] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][271] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][283] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][295] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[2]? arg[2][8] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][20] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][32] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][44] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][56] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][68] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][80] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][92] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][104] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][116] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][128] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][140] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][152] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][164] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][176] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][188] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][200] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][212] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][224] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][236] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][248] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][260] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][272] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][284] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][296] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[2]? arg[2][9] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][21] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][33] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][45] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][57] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][69] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][81] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][93] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][105] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][117] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][129] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][141] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][153] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][165] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][177] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][189] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][201] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][213] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][225] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][237] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][249] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][261] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][273] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][285] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][297] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[2]? arg[2][10] : 0;
  a00=(a00*a01);
  a02=arg[2]? arg[2][22] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[2]? arg[2][34] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[2]? arg[2][46] : 0;
  a02=(a02*a05);
  a00=(a00+a02);
  a02=arg[2]? arg[2][58] : 0;
  a02=(a02*a06);
  a00=(a00+a02);
  a02=arg[2]? arg[2][70] : 0;
  a02=(a02*a07);
  a00=(a00+a02);
  a02=arg[2]? arg[2][82] : 0;
  a02=(a02*a08);
  a00=(a00+a02);
  a02=arg[2]? arg[2][94] : 0;
  a02=(a02*a09);
  a00=(a00+a02);
  a02=arg[2]? arg[2][106] : 0;
  a02=(a02*a10);
  a00=(a00+a02);
  a02=arg[2]? arg[2][118] : 0;
  a02=(a02*a11);
  a00=(a00+a02);
  a02=arg[2]? arg[2][130] : 0;
  a02=(a02*a12);
  a00=(a00+a02);
  a02=arg[2]? arg[2][142] : 0;
  a02=(a02*a13);
  a00=(a00+a02);
  a02=arg[2]? arg[2][154] : 0;
  a02=(a02*a14);
  a15=arg[2]? arg[2][166] : 0;
  a15=(a15*a16);
  a02=(a02+a15);
  a15=arg[2]? arg[2][178] : 0;
  a15=(a15*a17);
  a02=(a02+a15);
  a15=arg[2]? arg[2][190] : 0;
  a15=(a15*a18);
  a02=(a02+a15);
  a15=arg[2]? arg[2][202] : 0;
  a15=(a15*a19);
  a02=(a02+a15);
  a15=arg[2]? arg[2][214] : 0;
  a15=(a15*a20);
  a02=(a02+a15);
  a15=arg[2]? arg[2][226] : 0;
  a15=(a15*a21);
  a02=(a02+a15);
  a15=arg[2]? arg[2][238] : 0;
  a15=(a15*a22);
  a02=(a02+a15);
  a15=arg[2]? arg[2][250] : 0;
  a15=(a15*a23);
  a02=(a02+a15);
  a15=arg[2]? arg[2][262] : 0;
  a15=(a15*a24);
  a02=(a02+a15);
  a15=arg[2]? arg[2][274] : 0;
  a15=(a15*a25);
  a02=(a02+a15);
  a15=arg[2]? arg[2][286] : 0;
  a15=(a15*a26);
  a02=(a02+a15);
  a00=(a00+a02);
  a02=arg[2]? arg[2][298] : 0;
  a00=(a00+a02);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[2]? arg[2][11] : 0;
  a00=(a00*a01);
  a01=arg[2]? arg[2][23] : 0;
  a01=(a01*a03);
  a00=(a00+a01);
  a01=arg[2]? arg[2][35] : 0;
  a01=(a01*a04);
  a00=(a00+a01);
  a01=arg[2]? arg[2][47] : 0;
  a01=(a01*a05);
  a00=(a00+a01);
  a01=arg[2]? arg[2][59] : 0;
  a01=(a01*a06);
  a00=(a00+a01);
  a01=arg[2]? arg[2][71] : 0;
  a01=(a01*a07);
  a00=(a00+a01);
  a01=arg[2]? arg[2][83] : 0;
  a01=(a01*a08);
  a00=(a00+a01);
  a01=arg[2]? arg[2][95] : 0;
  a01=(a01*a09);
  a00=(a00+a01);
  a01=arg[2]? arg[2][107] : 0;
  a01=(a01*a10);
  a00=(a00+a01);
  a01=arg[2]? arg[2][119] : 0;
  a01=(a01*a11);
  a00=(a00+a01);
  a01=arg[2]? arg[2][131] : 0;
  a01=(a01*a12);
  a00=(a00+a01);
  a01=arg[2]? arg[2][143] : 0;
  a01=(a01*a13);
  a00=(a00+a01);
  a01=arg[2]? arg[2][155] : 0;
  a01=(a01*a14);
  a14=arg[2]? arg[2][167] : 0;
  a14=(a14*a16);
  a01=(a01+a14);
  a14=arg[2]? arg[2][179] : 0;
  a14=(a14*a17);
  a01=(a01+a14);
  a14=arg[2]? arg[2][191] : 0;
  a14=(a14*a18);
  a01=(a01+a14);
  a14=arg[2]? arg[2][203] : 0;
  a14=(a14*a19);
  a01=(a01+a14);
  a14=arg[2]? arg[2][215] : 0;
  a14=(a14*a20);
  a01=(a01+a14);
  a14=arg[2]? arg[2][227] : 0;
  a14=(a14*a21);
  a01=(a01+a14);
  a14=arg[2]? arg[2][239] : 0;
  a14=(a14*a22);
  a01=(a01+a14);
  a14=arg[2]? arg[2][251] : 0;
  a14=(a14*a23);
  a01=(a01+a14);
  a14=arg[2]? arg[2][263] : 0;
  a14=(a14*a24);
  a01=(a01+a14);
  a14=arg[2]? arg[2][275] : 0;
  a14=(a14*a25);
  a01=(a01+a14);
  a14=arg[2]? arg[2][287] : 0;
  a14=(a14*a26);
  a01=(a01+a14);
  a00=(a00+a01);
  a01=arg[2]? arg[2][299] : 0;
  a00=(a00+a01);
  if (res[0]!=0) res[0][11]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int centroidal_mpc_hpipm_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int centroidal_mpc_hpipm_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int centroidal_mpc_hpipm_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void centroidal_mpc_hpipm_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int centroidal_mpc_hpipm_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void centroidal_mpc_hpipm_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void centroidal_mpc_hpipm_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void centroidal_mpc_hpipm_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int centroidal_mpc_hpipm_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int centroidal_mpc_hpipm_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real centroidal_mpc_hpipm_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* centroidal_mpc_hpipm_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* centroidal_mpc_hpipm_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* centroidal_mpc_hpipm_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* centroidal_mpc_hpipm_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int centroidal_mpc_hpipm_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int centroidal_mpc_hpipm_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
